language: python
#version
python:
  - "3.6"
cache: pip

services:
- postgresql

install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE fastfoodfast;" -U postgres
  - psql -c "CREATE DATABASE test_db;" -U postgres
  
script:
  - pytest -v --cov=app
after_success:
  - coveralls