language: python
#version
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE fastfoodfast;" -U postgres
  - psql -c "CREATE DATABASE test_db;" -U postgres
  
script:
  - pytest --cov=App
after_success:
  - coveralls
